import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { ViewTransitions } from 'next-view-transitions';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import Providers from '@/providers/query-provider';
import { Toaster } from 'sonner';
import NextTopLoader from 'nextjs-toploader';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn('h-full', 'antialiased', poppins.variable, 'font-sans')}
    >
      <body className="min-h-full flex flex-col">
        <ViewTransitions>
          <NextTopLoader showSpinner={false} color="#4fd1c5" />
          <Toaster position="top-center" />
          <Providers>{children}</Providers>
        </ViewTransitions>
      </body>
    </html>
  );
}
