import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '../globals.css';
import { cn } from '@/lib/utils';
import { ViewTransitions } from 'next-view-transitions';
import Providers from '@/providers/query-provider';
import { Toaster } from 'sonner';
import NextTopLoader from 'nextjs-toploader';
import { routing } from '../config/i18n';
import { notFound } from 'next/navigation';
import { getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as any)) notFound();

  const messages = await getMessages();
  return (
    <html
      lang={locale}
      className={cn('h-full', 'antialiased', poppins.variable, 'font-sans')}
    >
      <body className="min-h-full flex flex-col">
        <NextIntlClientProvider messages={messages}>
          <ViewTransitions>
            <NextTopLoader showSpinner={false} color="#4fd1c5" />
            <Toaster position="top-center" />
            <Providers>{children}</Providers>
          </ViewTransitions>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
