import '../globals.css';
import { Toaster } from 'sonner';
import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import { routing } from '../config/i18n';
import { notFound } from 'next/navigation';
import { Poppins } from 'next/font/google';
import NextTopLoader from 'nextjs-toploader';
import { getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';
import Providers from '@/providers/query-provider';
import { ViewTransitions } from 'next-view-transitions';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!routing.locales.includes(locale as any)) notFound();
  const messages = await getMessages();

  const cookieStore = await cookies();
  const theme = cookieStore.get('theme')?.value || 'system';

  const htmlClass =
    theme === 'dark' ? `dark ${poppins.variable}` : poppins.variable;

  return (
    <html suppressHydrationWarning lang={locale} className={htmlClass}>
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <NextIntlClientProvider messages={messages} locale={locale}>
          {/* <ThemeProvider
            attribute="class"
            defaultTheme={theme}
            disableTransitionOnChange
            storageKey="theme"
            enableSystem
          > */}
          <ViewTransitions>
            <NextTopLoader showSpinner={false} color="#4fd1c5" />
            <Toaster position="top-center" />
            <Providers>{children}</Providers>
          </ViewTransitions>
          {/* </ThemeProvider> */}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
